# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9cf38bc3-e7dc-4fed-a35d-722d809e246a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9cf38bc3-e7dc-4fed-a35d-722d809e246a".device = "/dev/disk/by-uuid/9cf38bc3-e7dc-4fed-a35d-722d809e246a";
  boot.initrd.luks.devices."luks-f1a17119-0aeb-481a-aab0-b7e03ac87ea3".device = "/dev/disk/by-uuid/f1a17119-0aeb-481a-aab0-b7e03ac87ea3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7CFD-14AB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/901cab6b-a0a9-4943-8750-d285c7a40892"; }
    ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  #hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
